go.property("id", 1)
go.property("track", 1)
go.property("switcher", false)
go.property("connector_index", 0)
go.property("bonus", 0)


function init(self)
	local parent =go.get_parent()

	local position = go.get_world_position(".")
	msg.post("/go", "point", {
		position = position,
		track = self.track,
		switcher = self.switcher,
		connector = self.connector_index,
		id = go.get_id(),
		number = self.id,
		bonus = self.bonus
	})
end